ASC.Web/Areas/Configuration/Models/MasterKeysViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASC.Web.Areas.Configuration.Models
{
    public class MasterKeysViewModel
    {
        public List<MasterDataKeyViewModel> MasterKeys { get; set; }
        public MasterDataKeyViewModel MasterKeyInContext { get; set; }
        public bool IsEdit { get; set; }
    }
}

ASC.Web/Areas/Configuration/Models/MasterValuesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASC.Web.Areas.Configuration.Models
{
    public class MasterValuesViewModel
    {
        public List<MasterDataValueViewModel> MasterValues { get; set; }
        public MasterDataValueViewModel MasterValueInContext { get; set; }
        public bool IsEdit { get; set; }
    }
}

ASC.Web/Areas/Configuration/Controllers/MasterDataController.cs
using ASC.Business.Interfaces;
using ASC.Models.Models;
using ASC.Utilities;
using ASC.Web.Areas.Configuration.Models;
using ASC.Web.Controllers;
using ASC.Web.Data;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ASC.Web.Areas.Configuration.Controllers
{
    [Area("Configuration")]
    [Authorize(Roles = "Admin")]
    public class MasterDataController : BaseController
    {
        private readonly IMasterDataOperations _masterData;
        private readonly IMapper _mapper;
        private readonly IMasterDataCacheOperations _masterDataCache;

        public MasterDataController(IMasterDataOperations masterData, IMapper mapper,
            IMasterDataCacheOperations masterDataCache)
        {
            this._masterData = masterData;
            this._mapper = mapper;
            this._masterDataCache = masterDataCache;
        }

        [HttpGet]
        public async Task<IActionResult> MasterKeys()
        {
            List<MasterDataKey> masterKeys = await this._masterData.GetAllMasterKeysAsync();
            List<MasterDataKeyViewModel> masterKeysViewModel = this._mapper
                .Map<List<MasterDataKey>, List<MasterDataKeyViewModel>>(masterKeys);

            // Hold all Master Keys in session
            HttpContext.Session.SetSession("MasterKeys", masterKeysViewModel);

            return View(new MasterKeysViewModel
            {
                //MasterKeys = masterKeysViewModel == null ? null : masterKeysViewModel.ToList(),
                //MasterKeys = masterKeysViewModel.Count != 0 ? masterKeysViewModel : null,
                MasterKeys = masterKeysViewModel != null ? masterKeysViewModel : null,
                IsEdit = false,
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MasterKeys(MasterKeysViewModel masterKeys)
        {
            masterKeys.MasterKeys = HttpContext.Session
                .GetSession<List<MasterDataKeyViewModel>>("MasterKeys");
            if (!ModelState.IsValid)
                return View(masterKeys);

            MasterDataKey masterKey = this._mapper
                .Map<MasterDataKeyViewModel, MasterDataKey>(masterKeys.MasterKeyInContext);
            if (masterKeys.IsEdit)
            {
                // Update Master Key
                await this._masterData
                    .UpdateMasterKeyAsync(masterKeys.MasterKeyInContext.PartitionKey, masterKey);
            }
            else
            {
                // Insert Master Key
                masterKey.RowKey = Guid.NewGuid().ToString();
                masterKey.PartitionKey = masterKey.Name;
                await this._masterData.InsertMasterKeyAsync(masterKey);
            }

            await this._masterDataCache.CreateMasterDataCacheAsync();
            return RedirectToAction("MasterKeys");
        }

        [HttpGet]
        public async Task<IActionResult> MasterValues()
        {
            // Get All Master Keys and hold them in ViewBag for Select tag
            ViewBag.MasterKeys = await this._masterData.GetAllMasterKeysAsync();

            return View(new MasterValuesViewModel
            {
                MasterValues = new List<MasterDataValueViewModel>(),
                IsEdit = false,
            });
        }

        [HttpGet]
        public async Task<IActionResult> MasterValuesByKey(string key)
        {
            // Get Master values based on master key.
            return Json(new { data = await this._masterData.GetAllMasterValuesByKeyAsync(key) });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MasterValues(bool isEdit, MasterDataValueViewModel masterValue)
        {
            if (!ModelState.IsValid)
                return Json("Error");

            MasterDataValue masterDataValue = this._mapper
                .Map<MasterDataValueViewModel, MasterDataValue>(masterValue);
            if (isEdit)
            {
                // Update Master Value
                await this._masterData.UpdateMasterValueAsync(masterDataValue.PartitionKey,
                    masterDataValue.RowKey, masterDataValue);
            }
            else
            {
                // Insert Master Value
                masterDataValue.RowKey = Guid.NewGuid().ToString();
                await this._masterData.InsertMasterValueAsync(masterDataValue);
            }

            await this._masterDataCache.CreateMasterDataCacheAsync();
            return Json(true);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UploadExcel()
        {
            IFormFileCollection files = Request.Form.Files;
            // Validations
            if (!files.Any())
                return Json(new { Error = true, Text = "Upload a file" });

            IFormFile excelFile = files.First();
            if(excelFile.Length <= 0)
                return Json(new { Error = true, Text = "Upload a file" });

            // Parse Excel Data
            List<MasterDataValue> masterData = await ParseMasterDataExcel(excelFile);
            bool result = await this._masterData.UploadBulkMasterData(masterData);

            await this._masterDataCache.CreateMasterDataCacheAsync();
            return Json(new { Success = result });
        }

        private async Task<List<MasterDataValue>> ParseMasterDataExcel(IFormFile excelFile)
        {
            List<MasterDataValue> masterValueList = new List<MasterDataValue>();
            using (MemoryStream memoryStream = new MemoryStream())
            {
                // Get MemoryStream from Excel file
                await excelFile.CopyToAsync(memoryStream);

                // Create a ExcelPackage object from MemoryStream
                using(ExcelPackage package = new ExcelPackage(memoryStream))
                {
                    // Get the first Excel sheet from the Workbook
                    ExcelWorksheet worksheet = package.Workbook.Worksheets[1];
                    int rowCount = worksheet.Dimension.Rows;

                    // Iterate all the rows and create the list of MasterDataValue
                    // Ignore first row as it is header
                    for (int row = 2; row <= rowCount; row++)
                    {
                        MasterDataValue masterDataValue = new MasterDataValue();
                        masterDataValue.RowKey = Guid.NewGuid().ToString();
                        masterDataValue.PartitionKey = worksheet.Cells[row, 1].Value.ToString();
                        masterDataValue.Name = worksheet.Cells[row, 2].Value.ToString();
                        masterDataValue.IsActive = Boolean
                            .Parse(worksheet.Cells[row, 3].Value.ToString());
                        masterValueList.Add(masterDataValue);
                    }
                }
            }

            return masterValueList;
        }
    }
}

ASC.Web/Areas/Configuration/Views/MasterData/MasterKeys.cshtml
@using ASC.Web.Areas.Configuration.Models;
@model MasterKeysViewModel
@{
    Layout = "_SecureLayout";
}

<div class="row"></div>
<div class="row padding-top-20px">
    <div class="row z-depth-3">
        <div class="section white-text padding-left-10px blue-grey lighten-1">
            <h5>Master Keys</h5>
        </div>
        <div class="divider"></div>
        <div class="col s12 padding-bottom-15px">
            @if (Model.MasterKeys != null)
            {
                <!-- Display List of Master Keys -->
                <table class="highlight centered" id="tblMasterKeys">
                    <thead>
                        <tr>
                            <th data-field="RowKey">Row Key</th>
                            <th data-field="PartitionKey">Partition Key</th>
                            <th data-field="Name">Name</th>
                            <th data-field="IsActive">Is Active</th>
                            <th data-field="IsActiveImg">Is Active</th>
                            <th data-field="Actions">Edit</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (MasterDataKeyViewModel masterKey in Model.MasterKeys)
                        {
                            <tr>
                                <td>@masterKey.RowKey</td>
                                <td>@masterKey.PartitionKey</td>
                                <td>@masterKey.Name</td>
                                <td>@masterKey.IsActive</td>
                                <td>
                                    <img src="@(masterKey.IsActive 
                                        ? "/images/green_tick.png" : "/images/red_cross.png")" />
                                </td>
                                <td>
                                    <i class="small material-icons edit cursor-hand">mode_edit</i>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <!-- In case of No records, display no records message -->
                <div class="card blue-grey lighten-1">
                    <div class="card-content white-text">
                        <span class="card-title">No Master Keys</span>
                        <p>No Master Keys found, please add a Master Key to the system.</p>
                    </div>
                </div>
            }
        </div>
    </div>

    <div class="row"></div>

    <!-- Details Section -->
    <div class="row z-depth-3">
        <div class="col s12 padding-0px">
            <div class="section white-text padding-left-10px blue-grey lighten-1">
                <h5>Master Key Details</h5>
            </div>
            <div class="divider"></div>
            <form asp-controller="MasterData" asp-action="MasterKeys" method="post"
                class="col s12" id="formMasterKey">
                <div class="row">
                    <input asp-for="IsEdit" type="hidden" />
                    <input asp-for="MasterKeyInContext.RowKey" type="hidden" />
                    <input asp-for="MasterKeyInContext.PartitionKey" type="hidden" />

                    <div class="input-field col s4">
                        <input asp-for="MasterKeyInContext.RowKey" id="Input_MasterKey_RowKey"
                               disabled="disabled" />
                        <label asp-for="MasterKeyInContext.RowKey"></label>
                    </div>
                    <div class="input-field col s4">
                        <input asp-for="MasterKeyInContext.Name" class="validate" />
                        <label asp-for="MasterKeyInContext.Name"></label>
                    </div>
                    <div class="input-field col s4">
                        <div class="switch">
                            <label>
                                Is Active
                                <input asp-for="MasterKeyInContext.IsActive" class="validate" />
                                <span class="lever"></span>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12 right-align">
                            <button class="btn waves-effect waves-light btnSubmit" type="submit"
                                name="action">
                                Create <i class="material-icons right">send</i>
                            </button>
                            <button class="btn waves-effect waves-light reset red lighten-1"
                                type="button" name="action">Reset</button>
                        </div>
                    </div>
                    <div asp-validation-summary="All" class="row col s12 right-align"></div>
                </div>
            </form>
        </div>
        <div class="row"></div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            // Initialize DataTable to show list of Engineers
            var table = $('#tblMasterKeys').DataTable({
                'pageLength': 3,
                // Number of records to be displayed per page
                'lengthMenu': [[3, 5, 10, -1], [3, 5, 10, 'All']],
            });

            // Set Styles for DataTable and Number of Records to be displayed in drop-down
            $('#tblMasterKeys').css('width', '100%');
            $('select[name="tblMasterKeys_length"]').material_select();

            // Get the column API object
            var partitionKeyColumn = table.column(1);
            partitionKeyColumn.visible(false);

            var isActiveColumn = table.column(3);
            isActiveColumn.visible(false);

            // Handle reset functionality
            $(document).on('click', '.reset', function () {
                $('#formMasterKey')[0].reset();
                $('.btnSubmit').text('Create');
                $('#IsEdit').val('False');
            });

            // On click of Edit icon, populate the details section with details of service engineer
            $(document).on('click', '.edit', function () {
                var user = $('#tblMasterKeys').DataTable().row($(this).parents('tr')).data();

                $('#IsEdit').val('True');
                // Map Row Key
                $('#MasterKeyInContext_RowKey').val(user[0]);
                $('#Input_MasterKey_RowKey').val(user[0]);
                // Map Partition Key
                $('#MasterKeyInContext_PartitionKey').val(user[1]);
                // Map Name
                $('#MasterKeyInContext_Name').val(user[2]);
                $('#MasterKeyInContext_Name').addClass('valid');
                // Map IsActive
                $('#MasterKeyInContext_IsActive').prop('checked', user[3] === 'True' ? true : false);

                $('.btnSubmit').text('Save');
                Materialize.updateTextFields();
            });
        });
    </script>
}